# Generated by Django 5.2.1 on 2025-05-27 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Active',
            new_name='is_active',
        ),
    ]
